#!/bin/sh
set -ex

# dep8 smoke test for entr
# Author: Otto Kekäläinen <otto@debian.org>
#
# This very simple test just checks that the binary starts and prints out
# the usage instructions, detected by keyword "usage".

entr -h 2>&1 | grep usage
